In [ ]:
# Импорт библиотеки NumPy
import numpy as np
print("NumPy успешно импортирован!")

# Создание массивов разными способами
print("\n--- Создание массивов ---")

# Из обычного списка
python_list = [1, 2, 3, 4, 5]
array_from_list = np.array(python_list)
print("Массив из списка:", array_from_list)

# Массив из нулей
zeros_array = np.zeros(5)
print("Массив из нулей:", zeros_array)

# Массив из единиц
ones_array = np.ones(5)
print("Массив из единиц:", ones_array)

# Массив с диапазоном
range_array = np.arange(0, 10, 2)
print("Массив с диапазоном:", range_array)

# Двумерный массив
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Двумерный массив:")
print(matrix_2d)

# Атрибуты массивов
print("\n--- Атрибуты массивов ---")
print("Форма array_from_list:", array_from_list.shape)
print("Тип данных array_from_list:", array_from_list.dtype)
print("Форма matrix_2d:", matrix_2d.shape)

# Индексирование и срезы
print("\n--- Индексирование и срезы ---")
arr = np.array([10, 20, 30, 40, 50, 60])
print("Исходный массив:", arr)
print("Первый элемент:", arr[0])
print("Элементы с 1-го по 4-й:", arr[0:3])
print("Вторая строка матрицы:", matrix_2d[1, :])

# Векторные операции и статистика
print("\n--- Векторные операции ---")
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("a + b:", a + b)
print("a * b:", a * b)

data = np.array([1.5, 2.7, 3.1, 4.8, 5.2])
print("Среднее значение:", np.mean(data))
print("Максимальное значение:", np.max(data))

NumPy успешно импортирован!

--- Создание массивов ---
Массив из списка: [1 2 3 4 5]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив из единиц: [1. 1. 1. 1. 1.]
Массив с диапазоном: [0 2 4 6 8]
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

--- Атрибуты массивов ---
Форма array_from_list: (5,)
Тип данных array_from_list: int64
Форма matrix_2d: (3, 3)

--- Индексирование и срезы ---
Исходный массив: [10 20 30 40 50 60]
Первый элемент: 10
Элементы с 1-го по 4-й: [10 20 30]
Вторая строка матрицы: [4 5 6]

--- Векторные операции ---
a + b: [ 6  8 10 12]
a * b: [ 5 12 21 32]
Среднее значение: 3.46
Максимальное значение: 5.2
